### ISSUE TITLE
bcc-lua error when running bashreadline.lua example

### ISSUE THREAD

**Issue by alext234** [iovisor/bcc#1621]
I have this error and no idea how to go about it:
```
$ sudo ./bashreadline.lua
[sudo] password for u:
[ERROR] bcc.lua:2287: bcc-lua: undefined symbol: bcc_resolve_symname
stack traceback:
        [C]: in function '__index'
        bcc.lua:2287: in function 'check_path_symbol'
        bcc.lua:2138: in function 'attach_uprobe'
        ./bashreadline.lua:21: in function <./bashreadline.lua:19>
        [C]: in function 'xpcall'
        bcc.lua:5913: in function <bcc.lua:5862>
        [C]: at 0x00744e10

```
On latest ubuntu server

```
lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

```

and latest bcc git
```
bcc$ git rev-parse HEAD
66db8790e3821779c803247f1faeef34c63751c7
```

**Comment by yonghong-song** [comment]
Looks like this is a CMake issue which is introduced sometimes back when CMakefiles are structured to allow CPP_API/USDT enabled/disabled. Will take a look.

**Comment by yonghong-song** [comment]
@alext234 could you try again with the latest bcc? Thanks!

**Comment by alext234** [comment]
Oh yep I did try it out and confirm the bug is fixed.

**Comment by yonghong-song** [comment]
@sandy-lcq Since you see the issue, could you help with a patch to fix it?

**Comment by sandy-lcq** [comment]
Hi, @yonghong-song 

I tried to make a patch,  but it seems not work.  After I apply my patch,  some symbols still not found.  I'm new to bcc, so maybe still need your help for this issue.

**Result:**
$ bcc-lua /usr/share/bcc/examples/lua/bashreadline.lua 
[ERROR] bcc.lua:2074: bcc-lua: **undefined symbol: bpf_module_create_c**
stack traceback:
	[C]: in function '__index'
	bcc.lua:2074: in function 'initialize'
	bcc.lua:1398: in function 'new'
	/usr/share/bcc/examples/lua/bashreadline.lua:20: in function </usr/share/bcc/examples/lua/bashreadline.lua:19>
	[C]: in function 'xpcall'
	bcc.lua:6333: in function <bcc.lua:6282>
	[C]: at 0x00404b50

**my patch:**
```
diff --git a/src/cc/CMakeLists.txt b/src/cc/CMakeLists.txt
index 104eff0e..f0f536f3 100644
--- a/src/cc/CMakeLists.txt
+++ b/src/cc/CMakeLists.txt
@@ -105,8 +105,6 @@ target_link_libraries(bcc-loader-static elf z)
 add_library(bcc-static STATIC
   ${bcc_common_sources} ${bcc_table_sources} ${bcc_util_sources} ${bcc_usdt_sources} ${bcc_sym_sources} ${bcc_util_sources})
 set_target_properties(bcc-static PROPERTIES OUTPUT_NAME bcc)
-set(bcc-lua-static
-  ${bcc_common_sources} ${bcc_table_sources} ${bcc_sym_sources} ${bcc_util_sources})
 
 set(bpf_sources libbpf.c perf_reader.c ${libbpf_sources} ${bcc_sym_sources} ${bcc_util_sources} ${bcc_usdt_sources})
 add_library(bpf-static STATIC ${bpf_sources})
@@ -177,7 +175,7 @@ target_sources(bcc-static PRIVATE $<TARGET_OBJECTS:clang_frontend-objects>)
 # Link against LLVM libraries
 target_link_libraries(bcc-shared ${bcc_common_libs_for_s})
 target_link_libraries(bcc-static ${bcc_common_libs_for_a} bcc-loader-static)
-set(bcc-lua-static ${bcc-lua-static} ${bcc_common_libs_for_lua})
+set(bcc-lua-static bcc-static ${bcc_common_libs_for_lua} PARENT_SCOPE)
 
 install(TARGETS bcc-shared bcc-static bcc-loader-static bpf-static LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
 install(FILES ${bcc_table_headers} DESTINATION include/bcc)
-- 
2.25.1
```

**compile command:**
/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot-native/usr/bin/x86_64-wrs-linux/x86_64-wrs-linux-gcc --sysroot=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/git=/usr/src/debug/bcc/0.29.1  -fdebug-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/git=/usr/src/debug/bcc/0.29.1  -fmacro-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/build=/usr/src/debug/bcc/0.29.1  -fdebug-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/build=/usr/src/debug/bcc/0.29.1  -fdebug-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot=  -fmacro-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot=  -fdebug-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot-native=  -Wall -DNDEBUG  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fcanon-prefix-map  -fmacro-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/git=/usr/src/debug/bcc/0.29.1  -fdebug-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/git=/usr/src/debug/bcc/0.29.1  -fmacro-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/build=/usr/src/debug/bcc/0.29.1  -fdebug-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/build=/usr/src/debug/bcc/0.29.1  -fdebug-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot=  -fmacro-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot=  -fdebug-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot-native=  -Wl,-z,relro,-z,now -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fcanon-prefix-map  -fmacro-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/git=/usr/src/debug/bcc/0.29.1  -fdebug-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/git=/usr/src/debug/bcc/0.29.1  -fmacro-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/build=/usr/src/debug/bcc/0.29.1  -fdebug-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/build=/usr/src/debug/bcc/0.29.1  -fdebug-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot=  -fmacro-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot=  -fdebug-prefix-map=/build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot-native=  -Wl,-z,relro,-z,now   -rdynamic src/lua/bcc.o src/lua/CMakeFiles/bcc-lua.dir/src/main.c.o -o **src/lua/bcc-lua  /build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot-native/usr/lib/libluajit-5.1.a  -Wl,-Bstatic  -ldl  -Wl,-Bdynamic  -lm  src/cc/libbcc.a  src/cc/frontends/clang/libclang_frontend.a  -lclang-cpp  /build/tmp-glibc/work/core2-64-wrs-linux/bcc/0.29.1/recipe-sysroot/usr/lib64/libLLVM.so.18.1  -lelf  -lbpf  src/cc/usdt/libusdt-static.a  -no-pie  -Wl,--whole-archive  -Wl,--no-whole-archive  -llzma  -ldebuginfod  -lbpf  src/cc/libbcc-loader-static.a  -lelf  -lz  -lstdc++  -lm**

Please see the bold part,  libbcc.a is linked, but still cannot be found in bcc-lua.

$ nm -a src/cc/libbcc.a | grep bpf_module_create_c
00000000000000b0 T bpf_module_create_c
0000000000000000 t bpf_module_create_c.cold
0000000000000220 T bpf_module_create_c_from_string
0000000000000049 t bpf_module_create_c_from_string.cold
$ nm -a src/lua/bcc-lua | grep bpf_module_create_c
$
