### ISSUE TITLE
Centos 7.6 Run opensnoop failed

### ISSUE THREAD

**Issue by kongsys** [iovisor/bcc#2368]
Is this the compiler problem? 
error log below:
/usr/share/bcc/tools/opensnoop -T
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:17:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/timex.h:56:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/uapi/linux/timex.h:56:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/time.h:5:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/seqlock.h:35:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/spinlock.h:50:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/preempt.h:9:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/thread_info.h:66:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/thread_info.h:22:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/cpufeature.h:7:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/processor.h:30:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/irqflags.h:15:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/irqflags.h:9:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/nospec-branch.h:12:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/jump_label.h:22:2: error: 'asm goto' constructs are not supported yet
        asm_volatile_goto("1:"
        ^
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/compiler-gcc.h:224:42: note: expanded from macro 'asm_volatile_goto'
#define asm_volatile_goto(x...) do { asm goto(x); asm (""); } while (0)
                                         ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:78:11: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
                return (set->sig[3] | set->sig[2] |
                        ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:78:25: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
                return (set->sig[3] | set->sig[2] |
                                      ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:79:4: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
                        set->sig[1] | set->sig[0]) == 0;
                        ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:81:11: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
                return (set->sig[1] | set->sig[0]) == 0;
                        ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:94:11: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
                return  (set1->sig[3] == set2->sig[3]) &&
                         ^         ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:94:27: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
                return  (set1->sig[3] == set2->sig[3]) &&
                                         ^         ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:95:5: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
                        (set1->sig[2] == set2->sig[2]) &&
                         ^         ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:95:21: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
                        (set1->sig[2] == set2->sig[2]) &&
                                         ^         ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:96:5: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
                        (set1->sig[1] == set2->sig[1]) &&
                         ^         ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:96:21: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
                        (set1->sig[1] == set2->sig[1]) &&
                                         ^         ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:99:11: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
                return  (set1->sig[1] == set2->sig[1]) &&
                         ^         ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:99:27: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
                return  (set1->sig[1] == set2->sig[1]) &&
                                         ^         ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:137:1: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigorsets, _sig_or)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:120:8: note: expanded from macro '_SIG_SET_BINOP'
                a3 = a->sig[3]; a2 = a->sig[2];                         \
                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:137:1: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigorsets, _sig_or)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:120:24: note: expanded from macro '_SIG_SET_BINOP'
                a3 = a->sig[3]; a2 = a->sig[2];                         \
                                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:137:1: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigorsets, _sig_or)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:121:8: note: expanded from macro '_SIG_SET_BINOP'
                b3 = b->sig[3]; b2 = b->sig[2];                         \
                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:137:1: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigorsets, _sig_or)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:121:24: note: expanded from macro '_SIG_SET_BINOP'
                b3 = b->sig[3]; b2 = b->sig[2];                         \
                                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:137:1: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigorsets, _sig_or)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:122:3: note: expanded from macro '_SIG_SET_BINOP'
                r->sig[3] = op(a3, b3);                                 \
                ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:137:1: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigorsets, _sig_or)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:123:3: note: expanded from macro '_SIG_SET_BINOP'
                r->sig[2] = op(a2, b2);                                 \
                ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:137:1: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigorsets, _sig_or)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:125:8: note: expanded from macro '_SIG_SET_BINOP'
                a1 = a->sig[1]; b1 = b->sig[1];                         \
                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:137:1: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigorsets, _sig_or)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:125:24: note: expanded from macro '_SIG_SET_BINOP'
                a1 = a->sig[1]; b1 = b->sig[1];                         \
                                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:137:1: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigorsets, _sig_or)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:126:3: note: expanded from macro '_SIG_SET_BINOP'
                r->sig[1] = op(a1, b1);                                 \
                ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:140:1: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandsets, _sig_and)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:120:8: note: expanded from macro '_SIG_SET_BINOP'
                a3 = a->sig[3]; a2 = a->sig[2];                         \
                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:140:1: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandsets, _sig_and)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:120:24: note: expanded from macro '_SIG_SET_BINOP'
                a3 = a->sig[3]; a2 = a->sig[2];                         \
                                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:140:1: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandsets, _sig_and)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:121:8: note: expanded from macro '_SIG_SET_BINOP'
                b3 = b->sig[3]; b2 = b->sig[2];                         \
                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:140:1: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandsets, _sig_and)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:121:24: note: expanded from macro '_SIG_SET_BINOP'
                b3 = b->sig[3]; b2 = b->sig[2];                         \
                                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:140:1: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandsets, _sig_and)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:122:3: note: expanded from macro '_SIG_SET_BINOP'
                r->sig[3] = op(a3, b3);                                 \
                ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:140:1: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandsets, _sig_and)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:123:3: note: expanded from macro '_SIG_SET_BINOP'
                r->sig[2] = op(a2, b2);                                 \
                ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:140:1: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandsets, _sig_and)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:125:8: note: expanded from macro '_SIG_SET_BINOP'
                a1 = a->sig[1]; b1 = b->sig[1];                         \
                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:140:1: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandsets, _sig_and)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:125:24: note: expanded from macro '_SIG_SET_BINOP'
                a1 = a->sig[1]; b1 = b->sig[1];                         \
                                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:140:1: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandsets, _sig_and)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:126:3: note: expanded from macro '_SIG_SET_BINOP'
                r->sig[1] = op(a1, b1);                                 \
                ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:143:1: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandnsets, _sig_andn)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:120:8: note: expanded from macro '_SIG_SET_BINOP'
                a3 = a->sig[3]; a2 = a->sig[2];                         \
                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:143:1: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandnsets, _sig_andn)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:120:24: note: expanded from macro '_SIG_SET_BINOP'
                a3 = a->sig[3]; a2 = a->sig[2];                         \
                                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:143:1: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandnsets, _sig_andn)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:121:8: note: expanded from macro '_SIG_SET_BINOP'
                b3 = b->sig[3]; b2 = b->sig[2];                         \
                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:143:1: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandnsets, _sig_andn)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:121:24: note: expanded from macro '_SIG_SET_BINOP'
                b3 = b->sig[3]; b2 = b->sig[2];                         \
                                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:143:1: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandnsets, _sig_andn)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:122:3: note: expanded from macro '_SIG_SET_BINOP'
                r->sig[3] = op(a3, b3);                                 \
                ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:143:1: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandnsets, _sig_andn)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:123:3: note: expanded from macro '_SIG_SET_BINOP'
                r->sig[2] = op(a2, b2);                                 \
                ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:143:1: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandnsets, _sig_andn)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:125:8: note: expanded from macro '_SIG_SET_BINOP'
                a1 = a->sig[1]; b1 = b->sig[1];                         \
                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:143:1: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandnsets, _sig_andn)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:125:24: note: expanded from macro '_SIG_SET_BINOP'
                a1 = a->sig[1]; b1 = b->sig[1];                         \
                                     ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:143:1: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_BINOP(sigandnsets, _sig_andn)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:126:3: note: expanded from macro '_SIG_SET_BINOP'
                r->sig[1] = op(a1, b1);                                 \
                ^      ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:167:1: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_OP(signotset, _sig_not)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:156:31: note: expanded from macro '_SIG_SET_OP'
            case 4: set->sig[3] = op(set->sig[3]);                      \
                                     ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:166:24: note: expanded from macro '_sig_not'
#define _sig_not(x)     (~(x))
                           ^
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:167:1: warning: array index 3 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_OP(signotset, _sig_not)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:156:14: note: expanded from macro '_SIG_SET_OP'
            case 4: set->sig[3] = op(set->sig[3]);                      \
                    ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:167:1: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_OP(signotset, _sig_not)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:157:24: note: expanded from macro '_SIG_SET_OP'
                    set->sig[2] = op(set->sig[2]);                      \
                                     ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:166:24: note: expanded from macro '_sig_not'
#define _sig_not(x)     (~(x))
                           ^
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:167:1: warning: array index 2 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_OP(signotset, _sig_not)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:157:7: note: expanded from macro '_SIG_SET_OP'
                    set->sig[2] = op(set->sig[2]);                      \
                    ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:167:1: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_OP(signotset, _sig_not)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:158:31: note: expanded from macro '_SIG_SET_OP'
            case 2: set->sig[1] = op(set->sig[1]);                      \
                                     ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:166:24: note: expanded from macro '_sig_not'
#define _sig_not(x)     (~(x))
                           ^
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:167:1: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
_SIG_SET_OP(signotset, _sig_not)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:158:14: note: expanded from macro '_SIG_SET_OP'
            case 2: set->sig[1] = op(set->sig[1]);                      \
                    ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:178:10: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
        case 2: set->sig[1] = 0;
                ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:190:10: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
        case 2: set->sig[1] = -1;
                ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:220:10: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
        case 2: set->sig[1] = 0;
                ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/sched.h:33:
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/include/linux/signal.h:232:10: warning: array index 1 is past the end of the array
      (which contains 1 element) [-Warray-bounds]
        case 2: set->sig[1] = -1;
                ^        ~
/lib/modules/3.10.0-957.12.2.el7.x86_64/build/arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];
        ^
49 warnings and 1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/opensnoop", line 137, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 318, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text

**Comment by kongsys** [comment]
i use pdb debug opensnoop, error occur at  `` b = BPF(text=bpf_text)```

**Comment by kongsys** [comment]
i have fixed this issue, form #2119 
i have edited  /usr/share/bcc/tools/opensnoop file, add some c program code at bpf_text head
```
#ifdef asm_volatile_goto
#undef asm_volatile_goto
#define asm_volatile_goto(x...)
#endif
```

**Comment by koxt** [comment]
Had the same issue, because of old bcc available version. (current v0.10.0)

```
cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

yum list bcc
bcc.x86_64                                                            0.6.1-2.el7                                                            base
```

**Comment by ibotheperfect** [comment]
I applied your solution. Errors lessen but still getting below errors. 
Only difference is I'm using self compiled kernel 5.0.13
Any suggestions?


# /usr/share/bcc/tools/opensnoop -T
In file included from <built-in>:3:
In file included from /virtual/include/bcc/helpers.h:23:
In file included from /lib/modules/5.0.13-1.lbr.x86_64/build/include/linux/log2.h:16:
In file included from /lib/modules/5.0.13-1.lbr.x86_64/build/include/linux/bitops.h:19:
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/bitops.h:209:9: error: 'asm goto' constructs are not supported yet
        return GEN_BINARY_RMWcc(LOCK_PREFIX __ASM_SIZE(bts), *addr, c, "Ir", nr);
               ^
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:60:32: note: expanded from macro 'GEN_BINARY_RMWcc'
#define GEN_BINARY_RMWcc(X...) RMWcc_CONCAT(GEN_BINARY_RMWcc_, RMWcc_ARGS(X))(X)
                               ^
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:10:28: note: expanded from macro 'RMWcc_CONCAT'
#define RMWcc_CONCAT(a, b) __RMWcc_CONCAT(a, b)
                           ^
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:9:30: note: expanded from macro '__RMWcc_CONCAT'
#define __RMWcc_CONCAT(a, b) a ## b
                             ^
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:54:2: note: expanded from macro 'GEN_BINARY_RMWcc_6'
        __GEN_RMWcc(op " %[val], " arg0, var, cc,                       \
        ^
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:21:2: note: expanded from macro '__GEN_RMWcc'
        asm_volatile_goto (fullop "; j" #cc " %l[cc_label]"             \
        ^
/lib/modules/5.0.13-1.lbr.x86_64/build/include/linux/compiler_types.h:188:37: note: expanded from macro 'asm_volatile_goto'
#define asm_volatile_goto(x...) asm goto(x)
                                    ^
In file included from <built-in>:3:
In file included from /virtual/include/bcc/helpers.h:23:
In file included from /lib/modules/5.0.13-1.lbr.x86_64/build/include/linux/log2.h:16:
In file included from /lib/modules/5.0.13-1.lbr.x86_64/build/include/linux/bitops.h:19:
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/bitops.h:255:9: error: 'asm goto' constructs are not supported yet
        return GEN_BINARY_RMWcc(LOCK_PREFIX __ASM_SIZE(btr), *addr, c, "Ir", nr);
               ^
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:60:32: note: expanded from macro 'GEN_BINARY_RMWcc'
#define GEN_BINARY_RMWcc(X...) RMWcc_CONCAT(GEN_BINARY_RMWcc_, RMWcc_ARGS(X))(X)
                               ^
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:10:28: note: expanded from macro 'RMWcc_CONCAT'
#define RMWcc_CONCAT(a, b) __RMWcc_CONCAT(a, b)
                           ^
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:9:30: note: expanded from macro '__RMWcc_CONCAT'
#define __RMWcc_CONCAT(a, b) a ## b
                             ^
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:54:2: note: expanded from macro 'GEN_BINARY_RMWcc_6'
        __GEN_RMWcc(op " %[val], " arg0, var, cc,                       \
        ^
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:21:2: note: expanded from macro '__GEN_RMWcc'
        asm_volatile_goto (fullop "; j" #cc " %l[cc_label]"             \
        ^
/lib/modules/5.0.13-1.lbr.x86_64/build/include/linux/compiler_types.h:188:37: note: expanded from macro 'asm_volatile_goto'
#define asm_volatile_goto(x...) asm goto(x)
                                    ^
In file included from <built-in>:3:
In file included from /virtual/include/bcc/helpers.h:23:
In file included from /lib/modules/5.0.13-1.lbr.x86_64/build/include/linux/log2.h:16:
In file included from /lib/modules/5.0.13-1.lbr.x86_64/build/include/linux/bitops.h:19:
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/bitops.h:308:9: error: 'asm goto' constructs are not supported yet
        return GEN_BINARY_RMWcc(LOCK_PREFIX __ASM_SIZE(btc), *addr, c, "Ir", nr);
               ^
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:60:32: note: expanded from macro 'GEN_BINARY_RMWcc'
#define GEN_BINARY_RMWcc(X...) RMWcc_CONCAT(GEN_BINARY_RMWcc_, RMWcc_ARGS(X))(X)
                               ^
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:10:28: note: expanded from macro 'RMWcc_CONCAT'
#define RMWcc_CONCAT(a, b) __RMWcc_CONCAT(a, b)
                           ^
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:9:30: note: expanded from macro '__RMWcc_CONCAT'
#define __RMWcc_CONCAT(a, b) a ## b
                             ^
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:54:2: note: expanded from macro 'GEN_BINARY_RMWcc_6'
        __GEN_RMWcc(op " %[val], " arg0, var, cc,                       \
        ^
/lib/modules/5.0.13-1.lbr.x86_64/build/arch/x86/include/asm/rmwcc.h:21:2: note: expanded from macro '__GEN_RMWcc'
        asm_volatile_goto (fullop "; j" #cc " %l[cc_label]"             \
        ^
/lib/modules/5.0.13-1.lbr.x86_64/build/include/linux/compiler_types.h:188:37: note: expanded from macro 'asm_volatile_goto'
#define asm_volatile_goto(x...) asm goto(x)
                                    ^
3 errors generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/opensnoop", line 141, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 318, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text

**Comment by yonghong-song** [comment]
Maybe this one?
https://github.com/iovisor/bcc/commit/a74c0429396f3180ba5b20f4a4eefc233b681cb4
